# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('journal', models.CharField(default='', max_length=200)),
                ('author_str', models.TextField(default='')),
                ('other_str', models.TextField(blank=True, default='', null=True)),
                ('citedby', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('doi', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pubmed', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('keyword_str', models.TextField(blank=True, default='', null=True)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('journal', models.CharField(default='', max_length=200)),
                ('author_str', models.TextField(default='')),
                ('other_str', models.TextField(blank=True, default='', null=True)),
                ('citedby', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('year', models.PositiveSmallIntegerField(default=0)),
                ('doi', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pubmed', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('keyword_str', models.TextField(blank=True, default='', null=True)),
                ('add2db', models.BooleanField(default=True)),
                ('addedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
